runtime:
  cache_dir: ./.cache/antora

site:
  title: OpenShift Starter Guides
  url: http://redhat-scholars.github.io/openshift-starter-guides/
  start_page: rhs-openshift-starter-guides::index.adoc

content:
  sources:
    - url: git@github.com:redhat-scholars/openshift-starter-guides.git
      tags: []
      branches: [ocp-4.8, ocp-4.9, ocp-4.11]
      start_path: documentation

asciidoc:
  attributes:
    #title: OpenShift Starter Guides
    experimental: true
    parksmap-version: latest
    parksmap-image: quay.io/openshiftroadshow/parksmap
    openshift-docs-url: https://docs.openshift.com/container-platform/4.11
    openshift-version: 4.11
    project-namespace: workshop
    release-version: roks
    roks-login-url: https://cloud.ibm.com/authorize/devcluster
    page-pagination: true
    lab: java
    lab-name: Java
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.8/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
