= Binary Builds
:navtitle: Binary Builds

[#moving_on_from_s2i]
== Moving on From S2I
As you saw before S2I is a great way to get from source code to a container, but the process is a bit too slow for daily fast iterative
development. For example, if you want to change some CSS or change one method in a class you don't want to go through
a full git commit and build cycle. In this lab we are going to show you a more efficient method for quick iteration. While
we are at it we will also show you how to debug your code.

Now that we built the MLB parks service let's go ahead and make some quick changes.

[#fast_iterative_code_change_using_binary_deploy]
== Fast Iterative Code Change Using Binary Deploy

The OpenShift command line has the ability to do a deployment from your local machine. In this case we are going to use S2I,
but we are going to tell OpenShift to just take the war file from our local machine and bake it in the image.

Doing this pattern of development lets us do quick builds on our local machine (benefitting from our local cache and
all the horsepower on our machine) and then just quickly send up the war file.

NOTE: You could also use this pattern to actually send up your working directory to the S2I builder to have it do the Maven build
on OpenShift. Using the local directory would relieve you from having Maven or any of the Java toolchain on your local
machine AND would also not require git commit with a push. Read more in the
{openshift-docs-url}/builds/basic-build-operations.html#builds-basic-start-source_basic-build-operations[official documentation]


[#using_binary_deployment]
== Exercise: Using Binary Deployment

[#clone_source]
=== Clone source
The first step is to clone the MLB source code from GitHub to your workshop environment:

[.console-input]
[source,bash]
----
git clone https://github.com/openshift-roadshow/mlbparks.git
----

NOTE: We are using Intellij here in the guide for screenshots but this should work regardless of your tool chain. JBoss
Developer Studio and JBoss Developer Tools have built in functionality that makes this close to seamless right from the IDE.

[#setup_the_build_of_the_war_file]
=== Setup the Build of the WAR file
If you have Maven all set up on your machine, then you can `cd` into the `mlbparks` directory and run `mvn package`

[#docker_for_maven]
[TIP]
====
If you don't have Maven on your machine but you are able to run docker, you can instead mount the repo directory and run the build commands from within the container.

. From within the directory that you ran `git clone` above, run the following command:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm --user 0 --name maven_builder -v ~/.kube:/home/jboss/.kube -v $(pwd):/workspaces -w /workspaces registry.access.redhat.com/ubi8/openjdk-11 /bin/bash
----
+
. Next, run this command (in the container) to locally install the latest version of `oc` on the container
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mkdir -p $HOME/bin && curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | \
    tar -xvzf - -C $HOME/bin/ oc && chmod 755 $HOME/bin/oc && ln -s $HOME/bin/oc $HOME/bin/kubectl
----
+
. Finally, ensure that you are still connected to your OpenShift cluster from within the builder container by running the following and comparing the output:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc whoami --show-server
----
+
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
https://%CLUSTER_SUBDOMAIN%:30713
----

Once completed, you should be able to follow the commands as they are outlined below.
====

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
cd mlbparks
mvn package
----

Pay attention to the output location for the ROOT.war, we will need that directory later.

[#code_change]
=== Code Change

Time for a source code change! 

Edit `BackendController` Java class from this path:

[.console-output]
[source,bash]
----
src/main/java/com/openshift/evg/roadshow/rest/BackendController.java
----

This is the REST endpoint that gives basic info on the service and can be reached at:

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-%PROJECT%.%CLUSTER_SUBDOMAIN%/ws/info/
----

Please change line 23 to add a _AMAZING_ in front of "MLB Parks" look like this:

[source,java]
----
return new Backend("mlbparks", "AMAZING MLB Parks", new Coordinates("39.82", "-98.57"), 5);
----

Don't forget to save the file and run `mvn package` again from the root of the source folder: 

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
mvn package
----

[#doing_the_binary_build]
=== Doing the Binary Build

Alright we have our war file built, time to kick off a build using it.

If you built your war with Maven:

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
oc start-build bc/mlbparks --from-file=target/ROOT.war --follow
----

NOTE: The --follow is optional if you want to follow the build output in your terminal.

Using labels and a recreate deployment strategy, as soon as the new deployment finishes the map name will be updated. Under a recreate deployment strategy we first tear down the pod before doing our new deployment.
When the pod is torn down, the parksmap service removes the MLBParks map from the layers. When it comes back up, the layer
automatically gets added back with our new title.  This would not have happened with a rolling deployment because
rolling spins up the new version of the pod before it takes down the old one. Rolling strategy enables a zero-downtime deployment.

You can follow the deployment in progress from Topology view, and when it is completed, you will see the new content at:

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-%PROJECT%.%CLUSTER_SUBDOMAIN%/ws/info/
----

So now you have seen how we can speed up the build and deploy process.
